### ISSUE TITLE
Solve that problem repository for .js 

### ISSUE THREAD

**Issue by NitkarshChourasia** [sach2212/-personal-website#4]
Solve those problems extensively from very_Easy.
Don't try to go the easy way but try to go the best way.
Start from 3, then go upto 10 a day.

**Comment by NitkarshChourasia** [comment]
@sach2212 We don't have time, only focus on few problems at least a day like 3, extras are more then welcomed.

**Comment by sach2212** [comment]
minimum target is 3  but the goal is to do more than 3 and  with the time I will keep increasing it

**Comment by NitkarshChourasia** [comment]
> minimum target is 3 but the goal is to do more than 3 and with the time I will keep increasing it

Good, count me in.

**Comment by sach2212** [comment]
kuch kaam se surat gaya tha bro
 today i will give you more than 3

**Comment by NitkarshChourasia** [comment]
surat...sahi hai.
