### ISSUE TITLE
Every Sunday.

### ISSUE THREAD

**Issue by NitkarshChourasia** [sach2212/-personal-website#5]
Every Sunday, we would have a little query session on video call.
my email address - playnitkarsh@gmail.com

Please register meeting for every Sunday, on **Zoom**.

**Comment by NitkarshChourasia** [comment]
@sach2212

**Comment by sach2212** [comment]
done mine is 
my email address - 2201sachin@gmail.com

**Comment by sach2212** [comment]
@NitkarshChourasia  in your Javascript file , the file name easy, in that all the problems starts with 395 
so do you have the problems from the scratch as well?

**Comment by NitkarshChourasia** [comment]
very_easy are 1-394

**Comment by NitkarshChourasia** [comment]
easy are from 395 to someNumerical.

**Comment by NitkarshChourasia** [comment]
They are in continuation series.

**Comment by sach2212** [comment]
actually very easy vala file is not there i think!
